sudo: required
language: java
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_bfaeaa986b9d_key -iv $encrypted_bfaeaa986b9d_iv -in travis/helseci2018-11-15.private.key.enc -out key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export INSTALLATION_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci2018-11-15.private.key.pem $GITHUB_APP_ID`)
script:
- make bump-version
- make
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- git config user.name team-helse[bot]
- git config user.email team-helse[bot]@users.noreply.github.com
- "./travis/push-tag.sh"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: F/8wx+UrwWUY3N0uFkicE0kwrKvH+L6NrygiTgDVhwA8weBd4MtXRADJyWex/YnoJAhcfVYjhjo2UmJgkL9yP8qi74cK+rbQDhut3QPZs/10XWFbOIeDS8ETV8tYInoN+m//lwdDeJMY1PxrUDP9T+OYEG7yGUMjcf08aVyCrsO7eZavoVYwRKuExOG2j8MfcZH246WLt5r9Zer6q4nR1dM8N6i75tuswreqUfGFHd4rYPsMKa8CmCuK4zDMD7KfOC859Q61h6cMSAnB31/027h31o8BHT4+wokAGVXNBM41Z/gANsQgk1qBE1JJv8feO4wgLUNcPYUY6FckBgP4ypn6EVETp+1JY9gJJ/htDjYPgomXTZj296DPOCqLRWIncMmflJyd5PEqc5DlYYeAYU9Ab/QrHkTaMESUlg5LGuUPB5iGEWXw6ZnBiCP9h45u5vdwxWKmm/FqiBGgwNrsOKwZvTldWPJPXgzFxQe+lhJV066PNOi3sXhPrBZlczhK9jTShZ0Rp/IMJ2r+XmpSYULaGMCaq4qSaormN1XHMo2b4TcPmjJ8VQGLDMbJz3NmNka8R9XphhBQhyqOiIG/8drSY31WeULbh+G+0X64gAoo7C7FMuXzsa63eTfTo80csiCQolwmM4yqxHgDzMyyxeq1wlu3g8whkPbYApGvgPM=
